<?php
/**
 * Core — explicit, user-confirmed complete data deletion (Construction
 * Order 009, Decision 019).
 *
 * Decision 019 requires that ASTREA Core's data survive plain plugin
 * deactivation/deletion by default (see uninstall.php, which is
 * intentionally a permanent no-op), and that a full, irreversible delete
 * only ever happen through an explicit, confirmed, in-product action. The
 * Remaining Work Audit (2026-08-27) found that action had never been
 * built across any prior Construction Order — this file is it.
 *
 * Deliberately lives on its own admin page, separate from every normal
 * settings screen, so a destructive action is never one click away from a
 * benign one (per the order's "通常設定から明確に分離された領域").
 *
 * Deletion inventory (Core-owned data only — see delete_all_core_data()):
 * Office Profile option; Professional Profile / Service / Price / FAQ /
 * Inquiry posts and their postmeta; the FAQ category taxonomy's terms;
 * Contact and SEO (incl. GA4) settings options; the Setup generated-pages
 * index option; Inquiry's two Cron schedules; three known transients.
 *
 * Explicitly NOT deleted, even though ASTREA created them: ordinary
 * WordPress Pages generated by Setup (事務所概要/料金/お問い合わせ/ホーム),
 * any generated Navigation, and Media Library attachments (Professional
 * Profile photos, the OGP image). These are user content per Decision
 * 016/019 — indistinguishable from anything else the site owner made by
 * hand, and never swept up by any Core deletion path, explicit or not.
 *
 * @package Astrea\Core
 */

namespace Astrea\Core\DataDeletion;

use function Astrea\Core\Inquiry\clear_cleanup_cron;
use function Astrea\Core\Inquiry\clear_digest_cron;
use const Astrea\Core\OfficeProfile\OPTION_NAME as OFFICE_PROFILE_OPTION;
use const Astrea\Core\ProfessionalProfile\POST_TYPE as PROFESSIONAL_POST_TYPE;
use const Astrea\Core\Service\POST_TYPE as SERVICE_POST_TYPE;
use const Astrea\Core\Price\POST_TYPE as PRICE_POST_TYPE;
use const Astrea\Core\Faq\POST_TYPE as FAQ_POST_TYPE;
use const Astrea\Core\Faq\TAXONOMY as FAQ_TAXONOMY;
use const Astrea\Core\Inquiry\POST_TYPE as INQUIRY_POST_TYPE;
use const Astrea\Core\Inquiry\SETTINGS_OPTION as CONTACT_SETTINGS_OPTION;
use const Astrea\Core\Inquiry\CLEANUP_LAST_RUN_TRANSIENT;
use const Astrea\Core\Inquiry\PENDING_EMAIL_TRANSIENT;
use const Astrea\Core\Seo\SETTINGS_OPTION as SEO_SETTINGS_OPTION;
use const Astrea\Core\Setup\GENERATED_PAGES_OPTION;
use const Astrea\Core\Setup\CONTACT_REACHABLE_TRANSIENT;

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Disallow direct access.
}

const PAGE_SLUG = 'astrea-core-data-deletion';

const DELETE_ACTION = 'astrea_delete_all_core_data';
const DELETE_NONCE  = 'astrea_delete_all_core_data_nonce';

/** The exact phrase a user must type to confirm — never accepted case-insensitively or partially. */
const CONFIRM_PHRASE = '削除する';

add_action( 'admin_menu', __NAMESPACE__ . '\\add_menu' );

/**
 * Registers the "データ削除" submenu, deliberately separate from every
 * other ASTREA settings screen.
 *
 * @return void
 */
function add_menu() {
	add_submenu_page(
		'astrea-core',
		__( 'データ削除', 'astrea-core' ),
		__( 'データ削除', 'astrea-core' ),
		'manage_options',
		PAGE_SLUG,
		__NAMESPACE__ . '\\render_page'
	);
}

/**
 * Renders the confirmation screen. No JavaScript-driven "enable on typing
 * the phrase" affordance — the phrase and checkbox are both re-validated
 * server-side regardless of what the form's own state shows, so this is a
 * genuine security control, not merely a UX nicety Client script could
 * bypass.
 *
 * @return void
 */
function render_page() {
	if ( ! current_user_can( 'manage_options' ) ) {
		wp_die( esc_html__( 'この画面を表示する権限がありません。', 'astrea-core' ) );
	}
	?>
	<div class="wrap">
		<h1><?php esc_html_e( 'データの完全削除', 'astrea-core' ); ?></h1>

		<?php settings_errors( 'astrea_core_data_deletion' ); ?>

		<div class="notice notice-warning inline">
			<p><strong><?php esc_html_e( 'この操作は元に戻せません。', 'astrea-core' ); ?></strong></p>
			<p><?php esc_html_e( '以下のASTREA Coreが保有するデータを完全に削除します。', 'astrea-core' ); ?></p>
			<ul style="list-style: disc; margin-left: 2em;">
				<li><?php esc_html_e( '事務所情報（Office Profile）', 'astrea-core' ); ?></li>
				<li><?php esc_html_e( '専門家プロフィール（Professional Profile）の全件', 'astrea-core' ); ?></li>
				<li><?php esc_html_e( '取扱業務（Service）の全件', 'astrea-core' ); ?></li>
				<li><?php esc_html_e( '料金（Price）の全件', 'astrea-core' ); ?></li>
				<li><?php esc_html_e( 'FAQ の全件とFAQカテゴリ', 'astrea-core' ); ?></li>
				<li><?php esc_html_e( '保存済みの問い合わせデータの全件', 'astrea-core' ); ?></li>
				<li><?php esc_html_e( '問い合わせ・SEO・GA4の設定', 'astrea-core' ); ?></li>
			</ul>
			<p><?php esc_html_e( '以下は削除しません（通常のWordPressコンテンツとして残ります）。', 'astrea-core' ); ?></p>
			<ul style="list-style: disc; margin-left: 2em;">
				<li><?php esc_html_e( 'Setupで作成した固定ページ（事務所概要・料金・お問い合わせ・ホーム等）', 'astrea-core' ); ?></li>
				<li><?php esc_html_e( '作成したNavigation（メニュー）', 'astrea-core' ); ?></li>
				<li><?php esc_html_e( 'メディアライブラリの画像（専門家の写真、OGP画像等）', 'astrea-core' ); ?></li>
			</ul>
		</div>

		<form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>">
			<input type="hidden" name="action" value="<?php echo esc_attr( DELETE_ACTION ); ?>" />
			<?php wp_nonce_field( DELETE_ACTION, DELETE_NONCE ); ?>
			<table class="form-table" role="presentation">
				<tr>
					<th scope="row"><?php esc_html_e( '確認', 'astrea-core' ); ?></th>
					<td>
						<label>
							<input type="checkbox" name="confirm_understood" value="1" />
							<?php esc_html_e( '上記の内容を理解し、元に戻せないことに同意します。', 'astrea-core' ); ?>
						</label>
					</td>
				</tr>
				<tr>
					<th scope="row">
						<label for="astrea_confirm_phrase">
							<?php
							printf(
								/* translators: %s: the literal confirmation phrase the user must type */
								esc_html__( '確認のため「%s」と入力してください', 'astrea-core' ),
								esc_html( CONFIRM_PHRASE )
							);
							?>
						</label>
					</th>
					<td>
						<input type="text" id="astrea_confirm_phrase" name="confirm_phrase" class="regular-text" autocomplete="off" />
					</td>
				</tr>
			</table>
			<?php submit_button( __( 'ASTREA Coreのデータを完全に削除する', 'astrea-core' ), 'delete' ); ?>
		</form>
	</div>
	<?php
}

add_action( 'admin_post_' . DELETE_ACTION, __NAMESPACE__ . '\\handle_delete' );

/**
 * Handles the confirmed deletion request. Refuses (redisplays the form
 * with an error, deletes nothing) unless every guard passes: capability,
 * Nonce, the checkbox, and an exact match of the typed phrase.
 *
 * @return void
 */
function handle_delete() {
	if ( ! current_user_can( 'manage_options' ) ) {
		wp_die( esc_html__( 'この操作を行う権限がありません。', 'astrea-core' ) );
	}

	check_admin_referer( DELETE_ACTION, DELETE_NONCE );

	$understood = isset( $_POST['confirm_understood'] ) && '1' === $_POST['confirm_understood'];
	$phrase     = isset( $_POST['confirm_phrase'] ) ? sanitize_text_field( wp_unslash( (string) $_POST['confirm_phrase'] ) ) : '';

	if ( ! $understood || CONFIRM_PHRASE !== $phrase ) {
		add_settings_error(
			'astrea_core_data_deletion',
			'astrea_data_deletion_not_confirmed',
			__( '確認内容が一致しないため、削除は行われませんでした。', 'astrea-core' )
		);
		set_transient( 'settings_errors', get_settings_errors(), 30 );
		wp_safe_redirect( admin_url( 'admin.php?page=' . PAGE_SLUG . '&settings-updated=1' ) );
		exit;
	}

	$deleted = delete_all_core_data();

	set_transient(
		'settings_errors',
		array(
			array(
				'setting' => 'astrea_core_data_deletion',
				'code'    => 'astrea_data_deletion_complete',
				'message' => sprintf(
					/* translators: %d: number of deleted posts across all Core post types */
					__( 'ASTREA Coreのデータを削除しました（投稿 %d件、設定・一時データを含む）。', 'astrea-core' ),
					$deleted['posts']
				),
				'type'    => 'success',
			),
		),
		30
	);
	wp_safe_redirect( admin_url( 'admin.php?page=' . PAGE_SLUG . '&settings-updated=1' ) );
	exit;
}

/**
 * Deletes every piece of Core-owned data. Idempotent and safe to run more
 * than once: each step queries for what currently exists rather than
 * acting on a fixed pre-computed list, so a second run (or a run that
 * picks up after an earlier one was interrupted, e.g. by a PHP timeout on
 * a very large Contact table) simply finds nothing left and does nothing
 * — there is no WordPress DB transaction to roll back, so resumability
 * stands in for a transaction guarantee.
 *
 * @return array{posts: int, options: int} Counts, for the confirmation message.
 */
function delete_all_core_data(): array {
	$posts_deleted = 0;

	foreach ( array( PROFESSIONAL_POST_TYPE, SERVICE_POST_TYPE, PRICE_POST_TYPE, FAQ_POST_TYPE, INQUIRY_POST_TYPE ) as $post_type ) {
		$posts_deleted += delete_all_posts_of_type( $post_type );
	}

	delete_faq_terms();

	$options_deleted = 0;
	foreach ( array( OFFICE_PROFILE_OPTION, CONTACT_SETTINGS_OPTION, SEO_SETTINGS_OPTION, GENERATED_PAGES_OPTION ) as $option_name ) {
		if ( delete_option( $option_name ) ) {
			++$options_deleted;
		}
	}

	delete_transient( CONTACT_REACHABLE_TRANSIENT );
	delete_transient( PENDING_EMAIL_TRANSIENT );
	delete_transient( CLEANUP_LAST_RUN_TRANSIENT );

	clear_cleanup_cron();
	clear_digest_cron();

	return array(
		'posts'   => $posts_deleted,
		'options' => $options_deleted,
	);
}

/**
 * Force-deletes (bypassing Trash) every post of a given Core-owned post
 * type, and its postmeta along with it (wp_delete_post()'s normal
 * behaviour). Deliberately never touches Media Library attachments — a
 * Professional Profile's featured image reference is removed with the
 * post, but the attachment itself is untouched, exactly like WordPress's
 * own "delete post" behaviour already treats featured images.
 *
 * @param string $post_type Post type to clear.
 * @return int Number of posts deleted.
 */
function delete_all_posts_of_type( string $post_type ): int {
	$deleted = 0;

	$post_ids = get_posts(
		array(
			'post_type'      => $post_type,
			'post_status'    => 'any',
			'posts_per_page' => -1,
			'fields'         => 'ids',
			'no_found_rows'  => true,
		)
	);

	foreach ( $post_ids as $post_id ) {
		if ( wp_delete_post( $post_id, true ) ) {
			++$deleted;
		}
	}

	return $deleted;
}

/**
 * Deletes every term of the FAQ category taxonomy.
 *
 * @return void
 */
function delete_faq_terms() {
	$terms = get_terms(
		array(
			'taxonomy'   => FAQ_TAXONOMY,
			'hide_empty' => false,
			'fields'     => 'ids',
		)
	);

	if ( is_wp_error( $terms ) ) {
		return;
	}

	foreach ( $terms as $term_id ) {
		wp_delete_term( $term_id, FAQ_TAXONOMY );
	}
}
