<?php
/**
 * ASTREA Starter Import — generated object ownership registry
 * (Construction 029-C Phase 11/12/13).
 *
 * Formalizes the `IMPORT_GENERATED_OPTION` contract Construction 029-A
 * proposed and Construction 029-B already read (as an opaque "is it
 * present and non-empty" signal) into a concrete schema. Construction
 * 029-C provides the write API; Construction 029-D is the first caller
 * that will actually register real generated objects — no Starter content
 * is generated by this Construction (see this file's tests, which
 * register plain integers, never real posts).
 *
 * Ownership invariants (Construction 029-C Phase 13):
 *   - Title/slug matching is never used for ownership — only this ID
 *     registry (and, where 029-D chooses to add it, object meta as a
 *     cross-check) counts as evidence of "ASTREA Starter Import made
 *     this".
 *   - The registry is never cleared just because an operation completed —
 *     ownership survives completion so a much later Reset/Reinstall
 *     (a future Construction, NOT this one) has something to act on.
 *   - Ownership is not permission to overwrite. Registering an object here
 *     records history; it grants no script anywhere the right to later
 *     mutate or delete that object without its own separate authorization
 *     check.
 *
 * @package Astrea\Core
 */

namespace Astrea\Core\StarterImport;

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Disallow direct access.
}

/** The registry option itself is Construction 029-A/029-B's `IMPORT_GENERATED_OPTION` — see starter-import-marker.php. */

/** The only object categories this registry accepts (Construction 029-C Phase 11). Anything else is rejected, not silently coerced. */
const OWNERSHIP_OBJECT_TYPES = array( 'posts', 'attachments', 'terms', 'navigation' );

/**
 * Option names Starter Import is known to legitimately own or modify
 * (Construction 028/029-A's existing `astrea_core_generated_*` pattern
 * plus the site-identity options `build-content.php` sets). This is a
 * closed allowlist specifically so `register_generated_option()` can never
 * be used to record ownership of an arbitrary, attacker- or bug-supplied
 * option name (Construction 029-C Phase 16, CASE O06).
 */
const OWNERSHIP_ALLOWED_OPTIONS = array(
	'astrea_core_office_profile',
	'astrea_core_generated_pages',
	'astrea_core_generated_navigation',
	'astrea_core_generated_template_parts',
	'blogname',
	'blog_public',
	'permalink_structure',
	'show_on_front',
	'page_on_front',
);

/**
 * The registry's shape when nothing has been recorded yet.
 *
 * @return array<string, mixed>
 */
function empty_ownership_registry(): array {
	return array(
		'schema_version'  => 1,
		'starter_version' => null,
		'operation_id'    => null,
		'objects'         => array(
			'posts'       => array(),
			'attachments' => array(),
			'terms'       => array(),
			'navigation'  => array(),
		),
		'options'         => array(),
	);
}

/**
 * Reads the current ownership registry, never mutating it. Malformed
 * stored data (e.g. from a future incompatible schema) falls back to an
 * empty registry rather than emitting a warning array shape callers must
 * defensively re-check — the registry is always well-formed to read.
 *
 * @return array<string, mixed>
 */
function get_ownership_registry(): array {
	$raw = get_option( IMPORT_GENERATED_OPTION, null );
	if ( ! is_array( $raw ) || ! isset( $raw['objects'] ) || ! is_array( $raw['objects'] ) ) {
		return empty_ownership_registry();
	}

	$registry                    = empty_ownership_registry();
	$registry['schema_version']  = $raw['schema_version'] ?? 1;
	$registry['starter_version'] = $raw['starter_version'] ?? null;
	$registry['operation_id']    = $raw['operation_id'] ?? null;

	foreach ( OWNERSHIP_OBJECT_TYPES as $type ) {
		if ( isset( $raw['objects'][ $type ] ) && is_array( $raw['objects'][ $type ] ) ) {
			$registry['objects'][ $type ] = array_values( array_unique( array_map( 'intval', $raw['objects'][ $type ] ) ) );
		}
	}

	if ( isset( $raw['options'] ) && is_array( $raw['options'] ) ) {
		$registry['options'] = array_values( array_unique( array_map( 'strval', $raw['options'] ) ) );
	}

	return $registry;
}

/**
 * Registers one generated object's ID under the given category.
 * Idempotent: registering the same (type, id) pair twice does not grow
 * the registry (Construction 029-C CASE O03).
 *
 * @param string $type One of OWNERSHIP_OBJECT_TYPES.
 * @param int    $id   The object's post ID (posts/attachments/navigation) or term ID (terms).
 * @return bool True if recorded (or already present), false if $type is invalid — rejected, not coerced (CASE O05).
 */
function register_generated_object( string $type, int $id ): bool {
	if ( ! in_array( $type, OWNERSHIP_OBJECT_TYPES, true ) ) {
		return false;
	}

	$registry = get_ownership_registry();

	if ( ! in_array( $id, $registry['objects'][ $type ], true ) ) {
		$registry['objects'][ $type ][] = $id;
	}

	save_ownership_registry( $registry );

	return true;
}

/**
 * Registers ownership of an option name Starter Import wrote to — but
 * ONLY if it appears on OWNERSHIP_ALLOWED_OPTIONS. An arbitrary,
 * unrecognized option name is rejected outright (Construction 029-C Phase
 * 16, CASE O06) rather than recorded as-is; there is no code path in this
 * module that lets a caller inject an unvetted option name into the
 * registry.
 *
 * @param string $option_name The option name to record ownership of.
 * @return bool True if recorded (or already present), false if rejected.
 */
function register_generated_option( string $option_name ): bool {
	if ( ! in_array( $option_name, OWNERSHIP_ALLOWED_OPTIONS, true ) ) {
		return false;
	}

	$registry = get_ownership_registry();

	if ( ! in_array( $option_name, $registry['options'], true ) ) {
		$registry['options'][] = $option_name;
	}

	save_ownership_registry( $registry );

	return true;
}

/**
 * Stamps the registry with the operation/version context it was created
 * under. Safe to call multiple times; does not touch already-registered
 * objects/options.
 *
 * @param string      $operation_id    This operation's ID.
 * @param string|null $starter_version The Starter Package version, if known.
 * @return void
 */
function stamp_ownership_registry_context( string $operation_id, ?string $starter_version ): void {
	$registry                    = get_ownership_registry();
	$registry['operation_id']    = $operation_id;
	$registry['starter_version'] = $starter_version;
	save_ownership_registry( $registry );
}

/**
 * Persists the registry. Internal — callers use the register_*() /
 * stamp_*() functions above, never this directly, so that every write
 * path stays subject to the same validation.
 *
 * @param array<string, mixed> $registry The registry to persist.
 * @return void
 */
function save_ownership_registry( array $registry ): void {
	update_option( IMPORT_GENERATED_OPTION, $registry );
}
